name: codes_postaux
description: "Recherche invers√©e de code postal"

publish_to: 'none'

version: 2.2.0+2

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  alphanum_comparator: ^2.0.3
  data_table_2: ^2.6.0
  flutter_native_splash: ^2.4.7
  http: ^1.6.0
  provider: ^6.1.5+1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android: true
  ios: false
  web: true